// <auto-generated />
using System;
using Filament_Db.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filament_Db.Migrations
{
    [DbContext(typeof(FilamentContext))]
    [Migration("20211214080433_ChangesV1_1")]
    partial class ChangesV1_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Filament_Db.Models.DensityAlias", b =>
                {
                    b.Property<int>("DensityAliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DefinedDensity")
                        .HasColumnType("REAL");

                    b.Property<int>("DensityType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilamentDefnId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DensityAliasId");

                    b.HasIndex("FilamentDefnId")
                        .IsUnique();

                    b.ToTable("DensityAliases");
                });

            modelBuilder.Entity("Filament_Db.Models.DepthMeasurement", b =>
                {
                    b.Property<int>("DepthMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdjustForWind")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Depth1")
                        .HasColumnType("REAL");

                    b.Property<double>("Depth2")
                        .HasColumnType("REAL");

                    b.Property<int>("InventorySpoolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeasureDateTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("PercentOffset")
                        .HasColumnType("REAL");

                    b.HasKey("DepthMeasurementId");

                    b.HasIndex("InventorySpoolId");

                    b.ToTable("DepthMeasurement");
                });

            modelBuilder.Entity("Filament_Db.Models.FilamentDefn", b =>
                {
                    b.Property<int>("FilamentDefnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsIntrinsic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShelfLifeInDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopUsing")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilamentDefnId");

                    b.ToTable("FilamentDefn");
                });

            modelBuilder.Entity("Filament_Db.Models.InventorySpool", b =>
                {
                    b.Property<int>("InventorySpoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilamentDefnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpoolDefnId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopUsing")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventorySpoolId");

                    b.HasIndex("FilamentDefnId");

                    b.HasIndex("SpoolDefnId");

                    b.ToTable("InventorySpools");
                });

            modelBuilder.Entity("Filament_Db.Models.MeasuredDensity", b =>
                {
                    b.Property<int>("MeasuredDensityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DensityAliasId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("MeasuredDensityId");

                    b.HasIndex("DensityAliasId");

                    b.ToTable("MeasuredDensity");
                });

            modelBuilder.Entity("Filament_Db.Models.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Filament_Db.Models.SpoolDefn", b =>
                {
                    b.Property<int>("SpoolDefnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DrumDiameter")
                        .HasColumnType("REAL");

                    b.Property<double>("SpoolDiameter")
                        .HasColumnType("REAL");

                    b.Property<double>("SpoolWidth")
                        .HasColumnType("REAL");

                    b.Property<bool>("StopUsing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendorDefnId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("SpoolDefnID");

                    b.HasIndex("VendorDefnId");

                    b.ToTable("SpoolDefn");
                });

            modelBuilder.Entity("Filament_Db.Models.VendorDefn", b =>
                {
                    b.Property<int>("VendorDefnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FoundOnAmazon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StopUsing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("VendorDefnId");

                    b.ToTable("VendorDefns");
                });

            modelBuilder.Entity("Filament_Db.Models.DensityAlias", b =>
                {
                    b.HasOne("Filament_Db.Models.FilamentDefn", "FilamentDefn")
                        .WithOne("DensityAlias")
                        .HasForeignKey("Filament_Db.Models.DensityAlias", "FilamentDefnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilamentDefn");
                });

            modelBuilder.Entity("Filament_Db.Models.DepthMeasurement", b =>
                {
                    b.HasOne("Filament_Db.Models.InventorySpool", "InventorySpool")
                        .WithMany("DepthMeasurements")
                        .HasForeignKey("InventorySpoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventorySpool");
                });

            modelBuilder.Entity("Filament_Db.Models.InventorySpool", b =>
                {
                    b.HasOne("Filament_Db.Models.FilamentDefn", "FilamentDefn")
                        .WithMany()
                        .HasForeignKey("FilamentDefnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Filament_Db.Models.SpoolDefn", "SpoolDefn")
                        .WithMany("Inventory")
                        .HasForeignKey("SpoolDefnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilamentDefn");

                    b.Navigation("SpoolDefn");
                });

            modelBuilder.Entity("Filament_Db.Models.MeasuredDensity", b =>
                {
                    b.HasOne("Filament_Db.Models.DensityAlias", "DensityAlias")
                        .WithMany("MeasuredDensity")
                        .HasForeignKey("DensityAliasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DensityAlias");
                });

            modelBuilder.Entity("Filament_Db.Models.SpoolDefn", b =>
                {
                    b.HasOne("Filament_Db.Models.VendorDefn", "Vendor")
                        .WithMany("SpoolDefns")
                        .HasForeignKey("VendorDefnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Filament_Db.Models.DensityAlias", b =>
                {
                    b.Navigation("MeasuredDensity");
                });

            modelBuilder.Entity("Filament_Db.Models.FilamentDefn", b =>
                {
                    b.Navigation("DensityAlias");
                });

            modelBuilder.Entity("Filament_Db.Models.InventorySpool", b =>
                {
                    b.Navigation("DepthMeasurements");
                });

            modelBuilder.Entity("Filament_Db.Models.SpoolDefn", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Filament_Db.Models.VendorDefn", b =>
                {
                    b.Navigation("SpoolDefns");
                });
#pragma warning restore 612, 618
        }
    }
}
