//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filament.WPF6.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filament.WPF6.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Inventory.
        /// </summary>
        public static string AddInventoryHeader {
            get {
                return ResourceManager.GetString("AddInventoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Density.
        /// </summary>
        public static string AverageDensityHeader {
            get {
                return ResourceManager.GetString("AverageDensityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Measured Density.
        /// </summary>
        public static string AverageMeasuredDensityHeader {
            get {
                return ResourceManager.GetString("AverageMeasuredDensityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string ColonHeader {
            get {
                return ResourceManager.GetString("ColonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorHeader {
            get {
                return ResourceManager.GetString("ColorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Editing Indicators.
        /// </summary>
        public static string DataEditingIndicatorsHeader {
            get {
                return ResourceManager.GetString("DataEditingIndicatorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Opened/Dried.
        /// </summary>
        public static string DateOpenedHeader {
            get {
                return ResourceManager.GetString("DateOpenedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined density as provided by vendor or website.
        /// </summary>
        public static string DefinedDensityToolTip {
            get {
                return ResourceManager.GetString("DefinedDensityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined.
        /// </summary>
        public static string DefinedHeader {
            get {
                return ResourceManager.GetString("DefinedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEI.
        /// </summary>
        public static string DEIHeader {
            get {
                return ResourceManager.GetString("DEIHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        public static string DensityHeader {
            get {
                return ResourceManager.GetString("DensityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gm per cc.
        /// </summary>
        public static string DensityInGmPerCCHeader {
            get {
                return ResourceManager.GetString("DensityInGmPerCCHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density Measurement Type.
        /// </summary>
        public static string DensityMeasurementTypeHeader {
            get {
                return ResourceManager.GetString("DensityMeasurementTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionHeader {
            get {
                return ResourceManager.GetString("DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string DiameterHeader {
            get {
                return ResourceManager.GetString("DiameterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found on Amazon :.
        /// </summary>
        public static string DisplayFoundOnAmazonHeader {
            get {
                return ResourceManager.GetString("DisplayFoundOnAmazonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string DisplayNameHeader {
            get {
                return ResourceManager.GetString("DisplayNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url :.
        /// </summary>
        public static string DisplayUrlHeader {
            get {
                return ResourceManager.GetString("DisplayUrlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum Diameter.
        /// </summary>
        public static string DrumDiameterToolTip {
            get {
                return ResourceManager.GetString("DrumDiameterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum.
        /// </summary>
        public static string DrumHeader {
            get {
                return ResourceManager.GetString("DrumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filament.
        /// </summary>
        public static string FilamentLabel {
            get {
                return ResourceManager.GetString("FilamentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filaments.
        /// </summary>
        public static string FilamentsHeader {
            get {
                return ResourceManager.GetString("FilamentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filament Type.
        /// </summary>
        public static string FilamentTypeHeader {
            get {
                return ResourceManager.GetString("FilamentTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found On Amazon.
        /// </summary>
        public static string FoundOnAmazonHeader {
            get {
                return ResourceManager.GetString("FoundOnAmazonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string LegendHeader {
            get {
                return ResourceManager.GetString("LegendHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LengthHeader {
            get {
                return ResourceManager.GetString("LengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured.
        /// </summary>
        public static string MeasuredHeader {
            get {
                return ResourceManager.GetString("MeasuredHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record needs to be saved to database..
        /// </summary>
        public static string NotInDbTip {
            get {
                return ResourceManager.GetString("NotInDbTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record in database..
        /// </summary>
        public static string RecordInDbTip {
            get {
                return ResourceManager.GetString("RecordInDbTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record is modified.
        /// </summary>
        public static string RecordModifiedToolTip {
            get {
                return ResourceManager.GetString("RecordModifiedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spool Definitions.
        /// </summary>
        public static string SpoolDefinitionsHeader {
            get {
                return ResourceManager.GetString("SpoolDefinitionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spool Depth.
        /// </summary>
        public static string SpoolDepthHeader {
            get {
                return ResourceManager.GetString("SpoolDepthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spool Diameter.
        /// </summary>
        public static string SpoolDiameterToolTip {
            get {
                return ResourceManager.GetString("SpoolDiameterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Using.
        /// </summary>
        public static string StopUsingHeader {
            get {
                return ResourceManager.GetString("StopUsingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop using this item.
        /// </summary>
        public static string StopUsingToolTip {
            get {
                return ResourceManager.GetString("StopUsingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Test {
            get {
                object obj = ResourceManager.GetObject("Test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Spool.
        /// </summary>
        public static string VendorSpoolHeader {
            get {
                return ResourceManager.GetString("VendorSpoolHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string VerifiedHeader {
            get {
                return ResourceManager.GetString("VerifiedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements verified on empty spool.
        /// </summary>
        public static string VerifiedToolTip {
            get {
                return ResourceManager.GetString("VerifiedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Address.
        /// </summary>
        public static string WebAddressHeader {
            get {
                return ResourceManager.GetString("WebAddressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page address.
        /// </summary>
        public static string WebAddressToolTip {
            get {
                return ResourceManager.GetString("WebAddressToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WeightHeader {
            get {
                return ResourceManager.GetString("WeightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filament weight in Kg.
        /// </summary>
        public static string WeightToolTip {
            get {
                return ResourceManager.GetString("WeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthHeader {
            get {
                return ResourceManager.GetString("WidthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner width of spool.
        /// </summary>
        public static string WidthToolTip {
            get {
                return ResourceManager.GetString("WidthToolTip", resourceCulture);
            }
        }
    }
}
