//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filament.WPF6.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black,White,Cyan,Yellow,Silver,Gray,Red,Lime,Blue,Teal,Purple,Olive,Maroon,Green," +
            "Navy,Orange,Gold,RoyalBlue,MediumBlue")]
        public string SupportedColors {
            get {
                return ((string)(this["SupportedColors"]));
            }
            set {
                this["SupportedColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SqlServer")]
        public string DataAccessSelector {
            get {
                return ((string)(this["DataAccessSelector"]));
            }
            set {
                this["DataAccessSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SqlServerNeedsMigration {
            get {
                return ((bool)(this["SqlServerNeedsMigration"]));
            }
            set {
                this["SqlServerNeedsMigration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExpandNodesOnStartup {
            get {
                return ((bool)(this["ExpandNodesOnStartup"]));
            }
            set {
                this["ExpandNodesOnStartup"] = value;
            }
        }
    }
}
